# Generated by Django 5.2.7 on 2025-11-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
